### PR TITLE
Inline validation and form restructuring

### PR DESCRIPTION
**Pull request by EddieDover**
@Lefteous I'm making this a Draft PR so you can decide whether you want to go through with it or not. It's a branch off of the currently open PR, so ignore the double-commit messages. I tried to be as gentle as possible with the restructring.

Changes:
- I've converted the HTML to Handlebars so we can get some better templating support, this allows us to inject errors and previously attempted values back into the form without forcing it to close and reopen. Attempting to enter invalid values and clicking Roll will result in the errors being displayed inline.
- Alongside the Handlebars conversion, I also converted the Dialog to a FormApplication object so we can take full advantage of Handlebars.
- I cleaned up the macro support and got rid of many functions that aren't necessary anymore, as well as some of the regex.
- I've added CSS support to the module file.
- I've moved the Hooks to a central location

If you have any questions, please let me know. After we've discussed, and you're comfortable with the changes, I can make this a full PR if you wish to consider merging.

### CODE REVIEW

**Comment by EddieDover** [comment]
Actually, I just realized what you were trying to do with the target comparison function, so I need to add that back in, in general.

**Comment by EddieDover** [comment]
I've restored conditional formatting and tested things a bit. I think this PR is far superior to the other, @Lefteous . You are welcome to test when you have time. 

I've included my unit tests file for completion’s sake; however, I need to figure out a way that you can run them.  To make things a bit easier on myself, the parent folder containing your repository on my local machine, has all the configuration to allow linting, testing, etc. (using package.json with node).  There's no way I can reflect that setup here without moving your module.json and that would break your plugin for anyone who currently has it installed. I'm a fan of non-destructive changes and backwards compatibility. 😁

**Comment by EddieDover** [comment]
In regards to the testing, if you install jest globally (npm install --global jest) then you -should- be able to run the tests with `NODE_OPTIONS="$NODE_OPTIONS --experimental-vm-modules" npx jest`

**Comment by Lefteous** [comment]
Heck yeah. I should have some time soon this evening to test everything.
Nothing like staring at code all day at work to then look at code all evening for fun.

**Comment by Lefteous** [comment]
@EddieDover This is working great. I need to probably set up the testing stuff on my other system or debug on this one because it continually fails to run jest for some reason without any good error.
 
That said running the module with your changes is working well. I only have one pedantic request which we'll probably want to phase out later. 

When running a roll that is outside the range of the formula you get the error inline with the dialog. If I change that to be within the range and roll, but the max roll attempts are reached it leaves the range error in the dialog box and throws the max attempt error to a blind DM card. Let me know what you think, but it might be best to throw that error into the dialog as well? It feels silly to put in a clear for the existing error text because if roll works the dialog box goes away, but still might be best in practice. 

I really dislike the max roll attempts and I'm certain there are better ways to handle the way it loads the dice so that's definitely going to be on my rework list. 

image

**Comment by EddieDover** [comment]
@Lefteous Due to how Handlebars works, we can only render the form once between draw calls, so rendering twice inside of that function won't do anything.  I've moved that whisper to an error message and done what I can to mitigate the issue, let me know what you think?

Also, are you not seeing CSS on your end?

image

**Comment by Lefteous** [comment]
Oh fascinating, the `styles.css` is applying fine in my local Foundry environment but on my live site it's not. That's where I took that screenshot. I didn't even notice it not working there hahah. I'll see if I can pinpoint why it's doing that. I don't think I have any other modules that would be messin with that but I see that `styles.css` isn't getting attached at all.

The new error handling for the max attempts works well though. Don't see any issues with that.

**Comment by EddieDover** [comment]
Yeah technically we should be naming everything like loaded-dice-roll.* to prevent conflicts so there's a chance something could be overwhelming something somewhere.

**Comment by Lefteous** [comment]
Ah, I just wiped that folder from my server, pushed it up again, and this time it worked fine. Unsure what the reason is for that but hey, we ball.

**Comment by Lefteous** [comment]
Want to add `loaded-dice-roll*` to your css and then I think this is a good merge.

**Comment by EddieDover** [comment]
> Want to add `loaded-dice-roll*` to your css and then I think this is a good merge?

I think we're good enough for now. If anyone does report an issue we can bug fix.

**Comment by Lefteous** [comment]
Great I'll go ahead and merge. 
Great quality of life stuff in here so I'll probably get a release ready for it too.

Appreciate the work!

**Review by Lefteous — APPROVED** [review]
Everything working as expected locally and on a live-use server. 
Will need to attempt running the tests again on a different/debugged machine for sake of future PRs. (Higher up on my to-do list)

Closes #3

**Pull request merged**
